### ISSUE TITLE
Playtesting Feedback: Rhys Angelo-Jones

### ISSUE THREAD

**Issue by nsHeresy** [Nickel64/Singularity-Group-Project#18]
Name: Rhys Angelo-Jones

Movement is a little sluggish - mouse sensitivity in particular could be increased.
Wasn’t sure what the red square was.
Wasn’t aware I was leaving boundy.
Didn’t know ship health.
A bit I think has a lot of potential is when I was flying through the rotating tower - felt exciting even with the less responsive controls.

**Comment by b-ran** [comment]
Rhys play test, like other player went outside the world boundary hence the game tried to kill which failed encountering the bug #28. In response we can chosen to add the teleporting via worm hole from on side of the to the other when leaving the boundary #24. The build played didn't display player health at all which Rhys wonder it was hence we plan to add health bar to the overlay #30. Also Rhys was confused on what the red square was which was the targeting system not working which has now being fixed.

**Comment by b-ran** [comment]
Feedback issues completed, closing
