### ISSUE TITLE
Playtesting Feedback: Chanil Park

### ISSUE THREAD

**Issue by nsHeresy** [Nickel64/Singularity-Group-Project#20]
Name: Chanil Park.

I think it would be great if there’s a main menu with instructions. If the space rocks/stone damages player, it would be more challenging. I wish you have some charging attack instead of missile. It is very fun to explore open world space but i don’t see enough contents to interact with.

**Comment by Fellarg** [comment]
Tutorial information could be as simple as one screen available in the main menu showing controls and with a simple rundown of game objectives, although a simplified version in the in game pause menu would be great to act as a quick reference. Collision causing damage to the player may increase difficulty which was lacking in the play testing version of the game, but could prove too much when the player is also under fire from enemies in an enclosed environment. Different weapon options are on the wish list for the game, but are currently out of scope. Interactivity has been greatly improved with the addition of enemy ships to shoot.

**Comment by b-ran** [comment]
Feedback issues completed, closing
