### ISSUE TITLE
Move player other side of boundary on collision

### ISSUE THREAD

**Issue by Fellarg** [Nickel64/Singularity-Group-Project#24]
related to #12

**Comment by Fellarg** [comment]
need to: 
find when player is near to the sphere.
open wormhole in their path.
find point on opposite side.
open wormhole on the opposite side.
ensure player direction is changed when they are teleported.

could:
have a warning when player gets close
have a nice effect when telleporting

**Comment by b-ran** [comment]
related feedback issue #21

**Comment by b-ran** [comment]
related feedback issue #18
