### ISSUE TITLE
Escape menu

### ISSUE THREAD

**Issue by b-ran** [Nickel64/Singularity-Group-Project#26]
This will need to be re-add with a focus of nicer textures and only using one canvas

**Comment by nsHeresy** [comment]
Menu Items: 
* Resume Game
* Controls
* Quit Game
* (Any other suggestions?)

**Comment by b-ran** [comment]
Should also include:
* Main Menu
* Settings

**Comment by b-ran** [comment]
Issue finished, settings for mouse sensitivity to come #36
